/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerNewRouteImport } from './routes/customer.new'
import { Route as ApiRewardsRouteImport } from './routes/api/rewards'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPointsRouteImport } from './routes/api/points'
import { Route as ApiPickupsRouteImport } from './routes/api/pickups'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNewRoute = CustomerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerRoute,
} as any)
const ApiRewardsRoute = ApiRewardsRouteImport.update({
  id: '/api/rewards',
  path: '/api/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPointsRoute = ApiPointsRouteImport.update({
  id: '/api/points',
  path: '/api/points',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPickupsRoute = ApiPickupsRouteImport.update({
  id: '/api/pickups',
  path: '/api/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/customer': typeof CustomerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/pickups': typeof ApiPickupsRoute
  '/api/points': typeof ApiPointsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rewards': typeof ApiRewardsRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer/': typeof CustomerIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/pickups': typeof ApiPickupsRoute
  '/api/points': typeof ApiPointsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rewards': typeof ApiRewardsRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer': typeof CustomerIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/customer': typeof CustomerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/pickups': typeof ApiPickupsRoute
  '/api/points': typeof ApiPointsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rewards': typeof ApiRewardsRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer/': typeof CustomerIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/customer'
    | '/profile'
    | '/rewards'
    | '/sitemap.xml'
    | '/vendor'
    | '/api/ai-chat'
    | '/api/chat'
    | '/api/messages'
    | '/api/pickups'
    | '/api/points'
    | '/api/profile'
    | '/api/rewards'
    | '/customer/new'
    | '/customer/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/profile'
    | '/rewards'
    | '/sitemap.xml'
    | '/api/ai-chat'
    | '/api/chat'
    | '/api/messages'
    | '/api/pickups'
    | '/api/points'
    | '/api/profile'
    | '/api/rewards'
    | '/customer/new'
    | '/customer'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/customer'
    | '/profile'
    | '/rewards'
    | '/sitemap.xml'
    | '/vendor'
    | '/api/ai-chat'
    | '/api/chat'
    | '/api/messages'
    | '/api/pickups'
    | '/api/points'
    | '/api/profile'
    | '/api/rewards'
    | '/customer/new'
    | '/customer/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorRoute: typeof VendorRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiPickupsRoute: typeof ApiPickupsRoute
  ApiPointsRoute: typeof ApiPointsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiRewardsRoute: typeof ApiRewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/new': {
      id: '/customer/new'
      path: '/new'
      fullPath: '/customer/new'
      preLoaderRoute: typeof CustomerNewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/api/rewards': {
      id: '/api/rewards'
      path: '/api/rewards'
      fullPath: '/api/rewards'
      preLoaderRoute: typeof ApiRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/points': {
      id: '/api/points'
      path: '/api/points'
      fullPath: '/api/points'
      preLoaderRoute: typeof ApiPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pickups': {
      id: '/api/pickups'
      path: '/api/pickups'
      fullPath: '/api/pickups'
      preLoaderRoute: typeof ApiPickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerRouteChildren {
  CustomerNewRoute: typeof CustomerNewRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerNewRoute: CustomerNewRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface VendorRouteChildren {
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CustomerRoute: CustomerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorRoute: VendorRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiPickupsRoute: ApiPickupsRoute,
  ApiPointsRoute: ApiPointsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiRewardsRoute: ApiRewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
