// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase as publicSupabase } from './client';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud. Falling back to public Supabase client.`;
    console.warn(`[Supabase] ${message}`);
    return publicSupabase;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

/**
 * Ensures required storage buckets exist.
 * This can be called from server functions to auto-provision buckets.
 */
export async function ensureBucketsExist() {
  const buckets = ['avatars', 'waste-photos'];
  const admin = _supabaseAdmin || createSupabaseAdminClient();

  for (const bucket of buckets) {
    try {
      const { data, error } = await admin.storage.getBucket(bucket);
      if (error && error.message && error.message.toLowerCase().includes('not found')) {
        console.log(`[Supabase] Creating missing bucket: ${bucket}`);
        const { error: createError } = await admin.storage.createBucket(bucket, {
          public: false,
          allowedMimeTypes: ['image/*'],
          fileSizeLimit: 5242880 // 5MB
        });
        if (createError) {
          console.error(`[Supabase] Failed to create bucket ${bucket}:`, createError.message);
        }
      }
    } catch (err) {
      console.error(`[Supabase] Error checking bucket ${bucket}:`, err);
    }
  }
}
